#mysql 주소 
spring.application.name=nori

spring.datasource.url=jdbc:mysql://localhost:3306/user_id?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.profiles.active=local
spring.datasource.username=root
spring.datasource.password=11111

# 서버가 켜질 때, 변경된 자바 설정(Auto Increment 등)을 DB에 반영하라는 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

