// src/utils/mockData.jsx
// 모든 Task 데이터를 한글 문자열 + 단순 필드 구조로 통일한 버전입니다.

export const mockTasks = [
  {
    id: '1',
    title: '로그인 페이지 UI 개선',
    description: '사용자 경험 향상을 위해 로그인 페이지 디자인을 개선합니다.',
    tags: ['UI', 'Frontend'],
    status: '진행 중',            // '할 일' | '진행 중' | '검토' | '완료'
    priority: '높음',             // '낮음' | '보통' | '높음' | '긴급'
    type: '기능',                 // '기능' | '버그' | '개선' | '문서'
    assignee: '김철수',
    dueDate: '2025. 12. 05.',
    project: '웹사이트 리뉴얼',
  },
  {
    id: '2',
    title: '회원가입 폼 버그 수정',
    description: '이메일 유효성 검사가 제대로 작동하지 않는 문제 수정',
    tags: ['Bug', 'Backend'],
    status: '할 일',
    priority: '긴급',
    type: '버그',
    assignee: '이영희',
    dueDate: '2025. 12. 01.',
    project: '웹사이트 리뉴얼',
  },
  {
    id: '3',
    title: 'API 문서 작성',
    description: 'REST API 엔드포인트에 대한 상세 문서 작성',
    tags: ['Documentation'],
    status: '검토',
    priority: '보통',
    type: '문서',
    assignee: '박민수',
    dueDate: '2025. 12. 10.',
    project: 'API 개발',
  },
  {
    id: '4',
    title: '데이터베이스 성능 최적화',
    description: '데이터베이스 쿼리 속도를 개선하기 위한 인덱스 최적화 작업',
    tags: ['Database', 'Performance'],
    status: '완료',
    priority: '높음',
    type: '개선',
    assignee: '정수진',
    dueDate: '2025. 11. 28.',
    project: 'Backend 최적화',
  },
  {
    id: '5',
    title: '모바일 반응형 개선',
    description: '태블릿 및 모바일 화면에서의 레이아웃 개선',
    tags: ['Mobile', 'UI'],
    status: '할 일',
    priority: '보통',
    type: '기능',
    assignee: '김철수',
    dueDate: '2025. 12. 15.',
    project: '웹사이트 리뉴얼',
  },
  {
    id: '6',
    title: '알림 기능 구현',
    description: '실시간 알림 시스템 개발',
    tags: ['Feature', 'Backend'],
    status: '진행 중',
    priority: '낮음',
    type: '기능',
    assignee: '이영희',
    dueDate: '2025. 12. 20.',
    project: 'API 개발',
  },
];
