// mockData.jsx
import { PRIORITY, TASK_STATUS, TASK_TYPE } from '../type/task';

/** @type {import('./task').User[]} */
export const mockUsers = [
  { id: '1', name: '김철수' },
  { id: '2', name: '이영희' },
  { id: '3', name: '박민수' },
  { id: '4', name: '정수진' },
];

/** @type {import('./task').Task[]} */
export const mockTasks = [
  {
    id: '1',
    title: '로그인 페이지 UI 개선',
    description: '사용자 경험 향상을 위해 로그인 페이지 디자인을 개선합니다.',
    priority: PRIORITY.HIGH,
    status: TASK_STATUS.IN_PROGRESS,
    type: TASK_TYPE.FEATURE,
    dueDate: new Date('2025-12-05'),
    assignee: mockUsers[0],
    coAssignees: [mockUsers[1]],
    tags: ['UI', 'Frontend'],
    project: '웹사이트 리뉴얼',
    subTasks: [
      { id: 's1', title: '디자인 시안 검토', completed: true },
      { id: 's2', title: 'UI 컴포넌트 구현', completed: false },
    ],
    attachments: [],
    customFields: {},
    createdAt: new Date('2025-11-28'),
    updatedAt: new Date('2025-11-30'),
  },
  {
    id: '2',
    title: '회원가입 폼 버그 수정',
    description: '이메일 유효성 검사가 제대로 작동하지 않는 문제 수정',
    priority: PRIORITY.URGENT,
    status: TASK_STATUS.TODO,
    type: TASK_TYPE.BUG,
    dueDate: new Date('2025-12-01'),
    assignee: mockUsers[1],
    coAssignees: [],
    tags: ['Bug', 'Backend'],
    project: '웹사이트 리뉴얼',
    subTasks: [],
    attachments: [],
    customFields: {},
    createdAt: new Date('2025-11-29'),
    updatedAt: new Date('2025-11-29'),
  },
  {
    id: '3',
    title: 'API 문서 작성',
    description: 'REST API 엔드포인트에 대한 상세 문서 작성',
    priority: PRIORITY.MEDIUM,
    status: TASK_STATUS.REVIEW,
    type: TASK_TYPE.DOCUMENTATION,
    dueDate: new Date('2025-12-10'),
    assignee: mockUsers[2],
    coAssignees: [mockUsers[0]],
    tags: ['Documentation'],
    project: 'API 개발',
    subTasks: [
      { id: 's3', title: '엔드포인트 목록 정리', completed: true },
      { id: 's4', title: '요청/응답 예시 작성', completed: true },
      { id: 's5', title: '에러 코드 정리', completed: false },
    ],
    attachments: [],
    customFields: {},
    createdAt: new Date('2025-11-25'),
    updatedAt: new Date('2025-11-29'),
  },
  {
    id: '4',
    title: '데이터베이스 성능 최적화',
    description: '쿼리 성능 개선 및 인덱스 추가',
    priority: PRIORITY.HIGH,
    status: TASK_STATUS.DONE,
    type: TASK_TYPE.IMPROVEMENT,
    dueDate: new Date('2025-11-28'),
    assignee: mockUsers[3],
    coAssignees: [],
    tags: ['Database', 'Performance'],
    project: 'API 개발',
    subTasks: [
      { id: 's6', title: '느린 쿼리 분석', completed: true },
      { id: 's7', title: '인덱스 추가', completed: true },
    ],
    attachments: [],
    customFields: {},
    createdAt: new Date('2025-11-20'),
    updatedAt: new Date('2025-11-28'),
  },
  {
    id: '5',
    title: '모바일 반응형 개선',
    description: '태블릿 및 모바일 화면에서의 레이아웃 개선',
    priority: PRIORITY.MEDIUM,
    status: TASK_STATUS.TODO,
    type: TASK_TYPE.FEATURE,
    dueDate: new Date('2025-12-15'),
    assignee: mockUsers[0],
    coAssignees: [mockUsers[2]],
    tags: ['Mobile', 'UI'],
    project: '웹사이트 리뉴얼',
    subTasks: [],
    attachments: [],
    customFields: {},
    createdAt: new Date('2025-11-30'),
    updatedAt: new Date('2025-11-30'),
  },
  {
    id: '6',
    title: '알림 기능 구현',
    description: '실시간 알림 시스템 개발',
    priority: PRIORITY.LOW,
    status: TASK_STATUS.IN_PROGRESS,
    type: TASK_TYPE.FEATURE,
    dueDate: new Date('2025-12-20'),
    assignee: mockUsers[1],
    coAssignees: [],
    tags: ['Feature', 'Backend'],
    project: 'API 개발',
    subTasks: [
      { id: 's8', title: 'WebSocket 서버 설정', completed: true },
      { id: 's9', title: '알림 UI 컴포넌트', completed: false },
    ],
    attachments: [],
    customFields: {},
    createdAt: new Date('2025-11-27'),
    updatedAt: new Date('2025-11-30'),
  },
];

/** @type {import('./task').Notification[]} */
export const mockNotifications = [
  {
    id: 'n1',
    type: 'due-soon',
    taskId: '2',
    taskTitle: '회원가입 폼 버그 수정',
    message: '내일까지 마감입니다',
    read: false,
    createdAt: new Date('2025-11-30T10:00:00'),
  },
  {
    id: 'n2',
    type: 'comment',
    taskId: '1',
    taskTitle: '로그인 페이지 UI 개선',
    message: '이영희님이 댓글을 남겼습니다',
    read: false,
    createdAt: new Date('2025-11-30T09:30:00'),
  },
  {
    id: 'n3',
    type: 'assigned',
    taskId: '5',
    taskTitle: '모바일 반응형 개선',
    message: '새로운 Task가 할당되었습니다',
    read: true,
    createdAt: new Date('2025-11-30T08:00:00'),
  },
];
